baseURL: "https://yaideltg.github.io/"
title: Poview
paginate: 4
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
defaultContentLanguage: 'en'
summaryLength: 50
copyright: 'This work is licensed under an Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license.'

# this is necessary for the search page
outputs:
  home:
    - HTML
    - RSS
    - JSON


minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series

        homeInfoParams:
          Title: "Hi there... 👋"
          Content: >
                 - Some writings mixed with photos... that\'s the plan.

                 - Thanks for stopping by. I hope you find something useful.

                 - Below other places where you can find and support my work.

        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                - name: Categories
                  url: categories/
                  weight: 20
                - name: About
                  url: about/
                  weight: 25

    es:
        languageName: "Español"
        weight: 2
        taxonomies:
          category: categories
          tag: tags
          series: series

        homeInfoParams:
            Title: "¿Qué welta? 💪"
            Content: >
                 - Escritos mezclados con fotos... al menos ese es el plan.

                 - Gracias por pasar. Espero que encuentres algo interesante.

                 - Aquí debajo dejo otros lugares donde puedes encontrar y apoyar mi trabajo.


        menu:
            main:
                - name: Archivo
                  url: archives
                  weight: 5
                - name: Buscar
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                - name: Categorias
                  url: categories/
                  weight: 20
                - name: About
                  url: about/
                  weight: 25

params:
    env: production
    description: Thanks for stopping by... hope you like it!
    author: Yaidel Toledo González
    # author: ["Me", "You"] # multiple authors
    hideFooter: false
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    socialIcons:
        - name: github
          url: "https://github.com/yaideltg"
        - name: paypal
          url: "https://paypal.me/yaidelytg"
        - name: donate
          url: "/donate"
        - name: email
          url: "/contact"
        - name: Rss
          url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    assets:
        disableHLJS: false
        # favicon: "/favicon.ico"
        # favicon16x16: "/favicon-16x16.png"
        # favicon32x32: "/favicon-32x32.png"
        # apple_touch_icon: "/apple-touch-icon.png"
        # safari_pinned_tab: "/safari-pinned-tab.svg"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: true # To enable hyperlinks to the full image size on post pages

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        lineNos: true
        style: emacs

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true